// src/routes/admin_draws.js
import express from "express";
import { getPool, query } from "../db/pg.js";
import { requireAuth, requireAdmin } from "../middleware/auth.js";

const router = express.Router();

router.use(requireAuth, requireAdmin);

let schemaReady = false;

/** Garante colunas/índices sem recriar tabelas existentes (compatível com seed antigo). */
async function ensureDrawsSchema() {
  if (schemaReady) return;

  await query(`ALTER TABLE draws ADD COLUMN IF NOT EXISTS product_name TEXT`);
  await query(`ALTER TABLE draws ADD COLUMN IF NOT EXISTS product_link TEXT`);
  await query(`ALTER TABLE draws ADD COLUMN IF NOT EXISTS banner_title TEXT`);
  await query(`ALTER TABLE draws ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'open'`);
  await query(
    `ALTER TABLE draws ADD COLUMN IF NOT EXISTS ticket_price_cents INTEGER DEFAULT 5500`
  );
  await query(
    `ALTER TABLE draws ADD COLUMN IF NOT EXISTS max_numbers_per_user INTEGER DEFAULT 5`
  );
  await query(`ALTER TABLE draws ADD COLUMN IF NOT EXISTS opened_at TIMESTAMPTZ DEFAULT NOW()`);
  await query(`ALTER TABLE draws ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ`);
  await query(`ALTER TABLE draws ADD COLUMN IF NOT EXISTS realized_at TIMESTAMPTZ`);
  await query(`ALTER TABLE draws ADD COLUMN IF NOT EXISTS winner_user_id BIGINT`);
  await query(`ALTER TABLE draws ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW()`);
  await query(`ALTER TABLE draws ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW()`);
  await query(`ALTER TABLE draws ADD COLUMN IF NOT EXISTS title TEXT`);
  await query(`ALTER TABLE draws ADD COLUMN IF NOT EXISTS prize_title TEXT`);
  await query(`ALTER TABLE draws ADD COLUMN IF NOT EXISTS promo_text TEXT`);
  await query(`ALTER TABLE draws ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ`);
  await query(`ALTER TABLE draws ADD COLUMN IF NOT EXISTS result_at TIMESTAMPTZ`);

  await query(`ALTER TABLE numbers ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'available'`);
  await query(`ALTER TABLE numbers ADD COLUMN IF NOT EXISTS user_id BIGINT`);
  await query(`ALTER TABLE numbers ADD COLUMN IF NOT EXISTS reservation_id TEXT`);
  await query(`ALTER TABLE numbers ADD COLUMN IF NOT EXISTS payment_id TEXT`);
  await query(`ALTER TABLE numbers ADD COLUMN IF NOT EXISTS reserved_until TIMESTAMPTZ`);
  await query(`ALTER TABLE numbers ADD COLUMN IF NOT EXISTS purchased_at TIMESTAMPTZ`);
  await query(
    `ALTER TABLE numbers ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW()`
  );

  await query(`
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'numbers'
          AND column_name = 'number'
      ) THEN
        EXECUTE 'UPDATE numbers SET n = number WHERE n IS NULL AND number IS NOT NULL';
      END IF;
    END $$;
  `);

  await query(`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'numbers' AND column_name = 'id'
      ) THEN
        ALTER TABLE numbers ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
      END IF;
    END $$;
  `);

  await query(`
    CREATE UNIQUE INDEX IF NOT EXISTS numbers_draw_id_n_uq
    ON numbers(draw_id, n);
  `);

  await query(`
    CREATE TABLE IF NOT EXISTS app_config (
      key TEXT PRIMARY KEY,
      value TEXT
    )
  `);

  schemaReady = true;
}

const OPEN_STATUSES = ["open", "active", "aberto", "ativo"];
const SOLD_STATUSES = ["paid", "sold", "approved", "pago", "vendido", "aprovado"];
const RESERVED_STATUSES = ["reserved", "pending", "reservado", "pendente"];
const FREE_STATUSES = ["available", "free", "livre", "disponivel", "disponível"];

const PAID_PAYMENT_STATUSES = ["approved", "paid", "pago"];

function toInt(value, fallback) {
  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function normalizeStatus(status) {
  const value = String(status || "").toLowerCase().trim();

  if (["open", "active", "ativo", "aberto"].includes(value)) return "open";
  if (["closed", "fechado", "finished", "encerrado", "finalizado"].includes(value))
    return "closed";
  if (["realized", "realizado", "done"].includes(value)) return "realized";
  if (["draft", "rascunho"].includes(value)) return "draft";

  return "open";
}

function toStatus(value) {
  const status = String(value || "").trim().toLowerCase();

  if (["open", "active", "aberto", "ativo"].includes(status)) return "open";
  if (["closed", "finished", "encerrado", "finalizado"].includes(status)) return "closed";
  if (["draft", "rascunho"].includes(status)) return "draft";

  return "closed";
}

async function insertNumbersForDraw(drawId) {
  await query(
    `
      INSERT INTO numbers (draw_id, n, status)
      SELECT $1, gs.n, 'available'
      FROM generate_series(0, 99) AS gs(n)
      ON CONFLICT (draw_id, n) DO NOTHING
    `,
    [drawId]
  );
}

async function ensureNumbersForDraw(client, drawId) {
  await client.query(
    `
    INSERT INTO numbers(draw_id, n, status)
    SELECT $1, gs, 'available'
    FROM generate_series(0, 99) AS gs
    ON CONFLICT (draw_id, n) DO NOTHING
    `,
    [drawId]
  );
}

async function ensureAdminSchemaCompat() {
  await ensureDrawsSchema();
  await query(`
    CREATE UNIQUE INDEX IF NOT EXISTS numbers_draw_id_n_unique
    ON numbers(draw_id, n)
  `);
}

// ── Listagem oficial “todos os sorteios” (deve vir ANTES de /:id) ──────────
router.get("/", async (req, res) => {
  try {
    await ensureDrawsSchema();

    const result = await query(`
      WITH number_summary AS (
        SELECT
          draw_id,
          COUNT(*)::INTEGER AS total_numbers,
          COUNT(*) FILTER (
            WHERE LOWER(COALESCE(status, 'available')) IN ('available', 'free', 'livre', 'disponivel', 'disponível')
          )::INTEGER AS available_numbers,
          COUNT(*) FILTER (
            WHERE LOWER(COALESCE(status, '')) IN ('reserved', 'reservado', 'pending', 'pendente')
          )::INTEGER AS reserved_numbers,
          COUNT(*) FILTER (
            WHERE LOWER(COALESCE(status, '')) IN ('paid', 'sold', 'approved', 'purchased', 'comprado', 'vendido', 'pago', 'aprovado')
          )::INTEGER AS sold_numbers
        FROM numbers
        GROUP BY draw_id
      )
      SELECT
        d.id,
        COALESCE(d.product_name, d.title, 'Sorteio #' || d.id) AS product_name,
        COALESCE(d.banner_title, d.promo_text, '') AS banner_title,
        COALESCE(d.status, 'open') AS status,
        COALESCE(d.ticket_price_cents, 5500)::INTEGER AS ticket_price_cents,
        COALESCE(d.max_numbers_per_user, 5)::INTEGER AS max_numbers_per_user,
        d.opened_at,
        d.closed_at,
        d.realized_at,
        d.created_at,
        COALESCE(ns.total_numbers, 0)::INTEGER AS total_numbers,
        COALESCE(ns.sold_numbers, 0)::INTEGER AS sold_numbers,
        GREATEST(
          COALESCE(ns.total_numbers, 100) - COALESCE(ns.sold_numbers, 0) - COALESCE(ns.reserved_numbers, 0),
          0
        )::INTEGER AS remaining_numbers,
        COALESCE(ns.reserved_numbers, 0)::INTEGER AS reserved_numbers,
        COALESCE(ns.available_numbers, 0)::INTEGER AS available_numbers,
        (COALESCE(ns.sold_numbers, 0) * COALESCE(d.ticket_price_cents, 5500))::INTEGER AS gmv_cents
      FROM draws d
      LEFT JOIN number_summary ns ON ns.draw_id = d.id
      ORDER BY d.id DESC;
    `);

    return res.json({
      ok: true,
      draws: result.rows,
    });
  } catch (error) {
    console.error("[admin/draws][GET /] erro:", error);
    return res.status(500).json({
      ok: false,
      error: error.message || "Erro ao listar sorteios.",
    });
  }
});

router.post("/", async (req, res) => {
  try {
    await ensureDrawsSchema();

    const productName =
      String(req.body?.product_name || req.body?.title || req.body?.name || "").trim() ||
      "Novo sorteio";

    const bannerTitle = String(
      req.body?.banner_title || req.body?.promo_text || req.body?.description || ""
    ).trim();

    const ticketPriceCents = toInt(
      req.body?.ticket_price_cents ?? req.body?.price_cents ?? req.body?.price,
      Number(process.env.PRICE_CENTS || 5500)
    );

    const maxNumbersPerUser = toInt(
      req.body?.max_numbers_per_user ?? req.body?.maxTicketsPerUser,
      Number(process.env.MAX_NUMBERS_PER_USER || 5)
    );

    const status = normalizeStatus(req.body?.status || "open");

    const created = await query(
      `
        INSERT INTO draws (
          product_name,
          banner_title,
          status,
          ticket_price_cents,
          max_numbers_per_user,
          opened_at,
          created_at,
          updated_at
        )
        VALUES ($1, $2, $3, $4, $5, NOW(), NOW(), NOW())
        RETURNING *;
      `,
      [productName, bannerTitle, status, ticketPriceCents, maxNumbersPerUser]
    );

    const draw = created.rows[0];

    await insertNumbersForDraw(draw.id);

    return res.status(201).json({
      ok: true,
      message: `Sorteio #${draw.id} criado com sucesso com números de 00 a 99.`,
      draw,
    });
  } catch (error) {
    console.error("[admin/draws][POST /] erro:", error);
    return res.status(500).json({
      ok: false,
      error: error.message || "Erro ao criar sorteio.",
    });
  }
});

// ── Rotas literais antes de /:id ───────────────────────────────────────────
router.get("/history", async (req, res) => {
  try {
    await ensureAdminSchemaCompat();

    const { rows } = await query(
      `
      SELECT
        d.id,
        d.title,
        d.prize_title,
        d.promo_text,
        d.status,
        d.ticket_price_cents,
        d.max_numbers_per_user,
        COALESCE(d.opened_at, d.started_at, d.created_at, NOW()) AS opened_at,
        d.closed_at,
        d.result_at,
        COUNT(*)::int AS total_numbers,
        COUNT(*) FILTER (WHERE LOWER(COALESCE(n.status, '')) = ANY($1))::int AS sold_numbers,
        COUNT(*) FILTER (WHERE LOWER(COALESCE(n.status, '')) = ANY($2))::int AS reserved_numbers,
        COUNT(*) FILTER (WHERE LOWER(COALESCE(n.status, '')) = ANY($3))::int AS free_numbers
      FROM draws d
      LEFT JOIN numbers n ON n.draw_id = d.id
      GROUP BY d.id
      ORDER BY d.id DESC
      `,
      [SOLD_STATUSES, RESERVED_STATUSES, FREE_STATUSES]
    );

    const draws = rows.map((row) => {
      const total = Number(row.total_numbers || 0);
      const sold = Number(row.sold_numbers || 0);
      const reserved = Number(row.reserved_numbers || 0);

      return {
        ...row,
        remaining_numbers: Math.max(0, total - sold - reserved),
      };
    });

    return res.json({
      ok: true,
      draws,
      history: draws,
    });
  } catch (err) {
    console.error("[admin.draws.history]", err);
    return res.status(500).json({
      ok: false,
      error: "admin_draws_history_failed",
      message: err.message,
    });
  }
});

async function handleDrawBuyers(req, res) {
  try {
    await ensureAdminSchemaCompat();

    const drawId = Number(req.params.id);

    if (!Number.isInteger(drawId) || drawId <= 0) {
      return res.status(400).json({
        ok: false,
        message: "ID do sorteio inválido.",
      });
    }

    const { rows } = await query(
      `
      SELECT
        COALESCE(u.id, 0) AS user_id,
        COALESCE(u.name, 'Sem usuário') AS name,
        COALESCE(u.email, '') AS email,
        COALESCE(u.phone, '') AS phone,
        COUNT(*)::int AS qtd,
        COUNT(*)::int AS quantity,
        COALESCE(
          json_agg(LPAD(num.n::text, 2, '0') ORDER BY num.n)
          FILTER (WHERE num.n IS NOT NULL),
          '[]'::json
        ) AS numbers,
        (COUNT(*)::int * COALESCE(d.ticket_price_cents, 5500))::int AS value_cents,
        (COUNT(*)::int * COALESCE(d.ticket_price_cents, 5500))::int AS amount_cents
      FROM payments p
      JOIN draws d ON d.id = p.draw_id
      JOIN users u ON u.id = p.user_id
      CROSS JOIN LATERAL unnest(p.numbers) AS num(n)
      WHERE p.draw_id = $1
        AND lower(trim(coalesce(p.status, ''))) = ANY($2)
      GROUP BY u.id, u.name, u.email, u.phone, d.ticket_price_cents
      ORDER BY qtd DESC, name ASC
      `,
      [drawId, PAID_PAYMENT_STATUSES]
    );

    return res.json({
      ok: true,
      buyers: rows,
      participants: rows,
      players: rows,
    });
  } catch (err) {
    console.error("[admin.draws.buyers]", err);
    return res.status(500).json({
      ok: false,
      error: "admin_draws_buyers_failed",
      message: err.message,
    });
  }
}

router.get("/:id/buyers", handleDrawBuyers);
router.get("/:id/participants", handleDrawBuyers);
router.get("/:id/players", handleDrawBuyers);

router.get("/:id/numbers", async (req, res) => {
  try {
    await ensureDrawsSchema();

    const drawId = toInt(req.params.id, null);

    if (!drawId) {
      return res.status(400).json({
        ok: false,
        error: "ID do sorteio inválido.",
      });
    }

    const result = await query(
      `
        SELECT
          id,
          draw_id,
          n,
          LPAD(n::TEXT, 2, '0') AS label,
          COALESCE(status, 'available') AS status,
          user_id,
          reservation_id,
          payment_id,
          reserved_until,
          purchased_at,
          created_at
        FROM numbers
        WHERE draw_id = $1
        ORDER BY n ASC;
      `,
      [drawId]
    );

    return res.json({
      ok: true,
      numbers: result.rows,
    });
  } catch (error) {
    console.error("[admin/draws][GET /:id/numbers] erro:", error);
    return res.status(500).json({
      ok: false,
      error: error.message || "Erro ao listar números.",
    });
  }
});

router.get("/:id", async (req, res) => {
  try {
    await ensureDrawsSchema();

    const drawId = toInt(req.params.id, null);

    if (!drawId) {
      return res.status(400).json({
        ok: false,
        error: "ID do sorteio inválido.",
      });
    }

    const result = await query(
      `
        SELECT
          id,
          COALESCE(product_name, title, 'Sorteio #' || id) AS product_name,
          COALESCE(banner_title, promo_text, '') AS banner_title,
          COALESCE(status, 'open') AS status,
          COALESCE(ticket_price_cents, 5500)::INTEGER AS ticket_price_cents,
          COALESCE(max_numbers_per_user, 5)::INTEGER AS max_numbers_per_user,
          opened_at,
          closed_at,
          realized_at,
          created_at
        FROM draws
        WHERE id = $1
        LIMIT 1;
      `,
      [drawId]
    );

    if (!result.rows[0]) {
      return res.status(404).json({
        ok: false,
        error: "Sorteio não encontrado.",
      });
    }

    return res.json({
      ok: true,
      draw: result.rows[0],
    });
  } catch (error) {
    console.error("[admin/draws][GET /:id] erro:", error);
    return res.status(500).json({
      ok: false,
      error: error.message || "Erro ao buscar sorteio.",
    });
  }
});

router.patch("/:id/status", async (req, res) => {
  const pool = await getPool();
  const client = await pool.connect();

  try {
    await ensureAdminSchemaCompat();

    const drawId = Number(req.params.id);

    if (!Number.isInteger(drawId) || drawId <= 0) {
      return res.status(400).json({
        ok: false,
        message: "ID do sorteio inválido.",
      });
    }

    const status = toStatus(req.body?.status);

    await client.query("BEGIN");

    if (status === "open") {
      await client.query(
        `
        UPDATE draws
        SET status = 'closed',
            closed_at = COALESCE(closed_at, NOW()),
            updated_at = NOW()
        WHERE LOWER(COALESCE(status, '')) = ANY($1)
          AND id <> $2
        `,
        [OPEN_STATUSES, drawId]
      );

      await client.query(
        `
        UPDATE draws
        SET status = 'open',
            opened_at = COALESCE(opened_at, NOW()),
            closed_at = NULL,
            updated_at = NOW()
        WHERE id = $1
        `,
        [drawId]
      );

      await ensureNumbersForDraw(client, drawId);

      await client.query(
        `
        INSERT INTO app_config(key, value)
        VALUES ('draw_id', $1), ('default_draw_id', $1)
        ON CONFLICT (key)
        DO UPDATE SET value = EXCLUDED.value
        `,
        [String(drawId)]
      );
    } else {
      const closed = status === "closed";
      await client.query(
        `
        UPDATE draws
        SET status = $2,
            closed_at = CASE
              WHEN $3 THEN COALESCE(closed_at, NOW())
              ELSE closed_at
            END,
            realized_at = CASE
              WHEN $2 = 'realized' THEN COALESCE(realized_at, NOW())
              ELSE realized_at
            END,
            updated_at = NOW()
        WHERE id = $1
        `,
        [drawId, status, closed]
      );
    }

    await client.query("COMMIT");

    return res.json({
      ok: true,
      id: drawId,
      status,
    });
  } catch (err) {
    await client.query("ROLLBACK").catch(() => {});
    console.error("[admin.draws.status]", err);
    return res.status(500).json({
      ok: false,
      error: "admin_draws_status_failed",
      message: err.message,
    });
  } finally {
    client.release();
  }
});

export default router;
